"use strict";

import { DataTypes, QueryInterface } from "sequelize";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    await queryInterface.bulkInsert("diccionario_financiero", [
      {
        id: 1,
        name: "CAJA Y BANCOS",
        code: "359",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 2,
        name: "INVERSIONES FINANCIERAS",
        code: "360",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 3,
        name: "CTAS X COBRAR - COMER - TERC.",
        code: "361",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 4,
        name: "CTAS X COBRAR - COMER - RELAC.",
        code: "362",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 5,
        name: "CTAS X COBR-PENS, ACC, SOC, DIC, GER",
        code: "363",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 6,
        name: "CUENTAS X COBRAR DIVERSAS - TERCEROS",
        code: "364",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 7,
        name: "CUENTAS X COBRAR RELACIONADAS",
        code: "365",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 8,
        name: "SERV. Y OTROS CONTRATS.  X ANTICIP.",
        code: "366",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 9,
        name: "ESTIMACION DE CTAS COBR. DUDOSA",
        code: "367",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 10,
        name: "MERCADERIAS",
        code: "368",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 11,
        name: "PRODUC. TERMINADOS",
        code: "369",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 12,
        name: "DESECHOS Y DESPERDICIOS",
        code: "370",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 13,
        name: "PRODUC. EN PROCESO",
        code: "371",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 14,
        name: "MATERIAS PRIMAS",
        code: "372",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 15,
        name: "MAT. AUXILIAR, SUMINS Y REPUESTOS",
        code: "373",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 16,
        name: "ENVASES Y EMBALAJES",
        code: "374",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 17,
        name: "EXISTENC. X RECIBIR",
        code: "375",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 18,
        name: "DESVALORIZACION DE EXISTENC.",
        code: "376",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 19,
        name: "ACTIVOS NO CTES MANTENIDO PARA LA VTA",
        code: "377",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 20,
        name: "OTROS ACTIVOS CORRIENTES",
        code: "378",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 21,
        name: "INVERSIONES INMOBILIARIAS",
        code: "379",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 22,
        name: "INVERSIONES MOBILIARIAS",
        code: "380",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 23,
        name: "ACTIVOS ADQUIR. EN LEASING",
        code: "381",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 24,
        name: "INM. MAQU. Y EQUIP.",
        code: "382",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 25,
        name: "DEPREC.  ACTVS LEASING E IME. ACUML.",
        code: "383",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 26,
        name: "INTANGIBLES",
        code: "384",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 27,
        name: "ACTIVOS BIOLOGICOS",
        code: "385",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 28,
        name: "DESVALORIZACION DE ACTIVOS",
        code: "386",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 29,
        name: "REVALOR. DE ACTVS INMOVILZADO",
        code: "387",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 30,
        name: "ACTIVO DIFERIDO",
        code: "388",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 31,
        name: "OTROS ACTIVOS NO CORRIENTES",
        code: "389",
        category: "Activo",
        group: "Balance General",
      },
      {
        id: 32,
        name: "SOBRE GIROS BANCARIOS",
        code: "401",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 33,
        name: "TRIB. APORT. SIST. PENS. SALUD X PAGAR",
        code: "402",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 34,
        name: "REMUNERAC. Y PARTIC. X PAGAR",
        code: "403",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 35,
        name: "CTAS POR PAGAR COMERC - TERCEROS.",
        code: "404",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 36,
        name: "CTAS POR PAGAR COMERC - RELAC.",
        code: "405",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 37,
        name: "CTAS POR PAGAR ACC, DIREC, Y GER.",
        code: "406",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 38,
        name: "CTAS POR PAGAR DIVERSAS - TERC.",
        code: "407",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 39,
        name: "CTAS POR PAGAR DIVERSAS  - RELAC.",
        code: "408",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 40,
        name: "OBLIGACIONES FINANCIERAS",
        code: "409",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 41,
        name: "PROVISIONES",
        code: "410",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 42,
        name: "PASIVO DIFERIDO",
        code: "411",
        category: "Pasivo",
        group: "Balance General",
      },
      {
        id: 43,
        name: "CAPITAL",
        code: "414",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 44,
        name: "ACCIONES DE INVERSION",
        code: "415",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 45,
        name: "Capital adicional positivo",
        code: "416",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 46,
        name: "Capital adicional negativo",
        code: "417",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 47,
        name: "RESULTADOS NO REALIZADOS",
        code: "418",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 48,
        name: "EXCEDENTE DE REVALUACION",
        code: "419",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 49,
        name: "RESERVAS",
        code: "420",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 50,
        name: "Resultados acumulados positivos",
        code: "421",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 51,
        name: "Resultados acumulados negativos",
        code: "422",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 52,
        name: "Utilidad del ejercicio",
        code: "423",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 53,
        name: "Pérdida del ejercicio",
        code: "424",
        category: "Patrimonio",
        group: "Balance General",
      },
      {
        id: 54,
        name: "VENTAS NETAS/ INGRESOS X SERV.",
        code: "461",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 55,
        name: "DESC. REBJ. Y BONIF. CONCEDIDAS",
        code: "462",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 56,
        name: "COSTO DE VENTAS",
        code: "464",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 57,
        name: "GASTOS DE VENTAS",
        code: "468",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 58,
        name: "GASTOS DE ADMINISTRACION",
        code: "469",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 59,
        name: "GASTOS FINANCIEROS",
        code: "472",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 60,
        name: "INGRESOS FINANCIEROS GRAVADOS",
        code: "473",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 61,
        name: "OTROS INGRESOS GRAVADOS",
        code: "475",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 62,
        name: "OTROS INGRESOS NO GRAVADOS",
        code: "476",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 63,
        name: "ENAJENC. Y DE VALR, Y BS. ACTV FIJO",
        code: "477",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 64,
        name: "COST ENAJ. Y DE VALR, Y BS. ACTV FIJO",
        code: "478",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 65,
        name: "GASTOS DIVERSOS",
        code: "480",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 66,
        name: "DISTRIBUCION LEGAL DE LA RENTA",
        code: "486",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 67,
        name: "IMPUESTO A LA RENTA",
        code: "490",
        category: "",
        group: "Estado de Resultados",
      },
      //Adicionales para Ratios
      {
        id: 68,
        name: "TOTAL ACTIVO CIRC.",
        code: "1000",
        category: "",
        group: "Balance General",
      },
      {
        id: 69,
        name: "TOTAL ACTIVO NO CIRC.",
        code: "1001",
        category: "",
        group: "Balance General",
      },
        {
        id: 70,
        name: "TOTAL PASIVO CIRC.",
        code: "412",
        category: "",
        group: "Balance General",
      },
        {
        id: 71,
        name: "TOTAL PASIVO NO CIRC.",
        code: "1003",
        category: "",
        group: "Balance General",
      },
      {
        id: 72,
        name: "Ventas netas",
        code: "463",
        category: "",
        group: "Balance General",
      },
      {
        id: 73,
        name: "TOTAL ACTIVOS",
        code: "390",
        category: "",
        group: "Balance General",
      },
      {
        id: 74,
        name: "RESULTADO DE OPERACIÓN",
        code: "1005",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 75,
        name: "UTILIDAD NETA",
        code: "1006",
        category: "",
        group: "Estado de Resultados",
      },
      {
        id: 76,
        name: "TOTAL PATRIMONIO",
        code: "425",
        category: "Patrimonio",
        group: "Balance General",
      },

    ]);
  },

  async down(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    await queryInterface.bulkDelete("diccionario_financiero", {}, {});
  },
};
